<a href="https://colab.research.google.com/github/mngugi/Code_3_Camp/blob/main/FinData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

financial_data = np.array([[100, 5, 500, 0.02], [120, 6, 550, 0.015],[90, 4, 480, 0.025]]).


In [1]:
import numpy as np

financial_data = np.array([[100, 5, 500, 0.02], [120, 6, 550, 0.015], [90, 4, 480, 0.025]])

# Transpose the data to have features in columns
financial_data_transposed = financial_data.T

# Calculate the covariance matrix
covariance_matrix = np.cov(financial_data_transposed)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[ 2.33333333e+02  1.50000000e+01  5.50000000e+02 -7.50000000e-02]
 [ 1.50000000e+01  1.00000000e+00  3.50000000e+01 -5.00000000e-03]
 [ 5.50000000e+02  3.50000000e+01  1.30000000e+03 -1.75000000e-01]
 [-7.50000000e-02 -5.00000000e-03 -1.75000000e-01  2.50000000e-05]]
