<a href="https://colab.research.google.com/github/mngugi/Code_3_Camp/blob/main/MatrixRecap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

revenue = np.array([[180,200,220],[240,360,400],[220,400,200]])
expensenses = np.array([[80,10,8],[90,16,10],[100,20,10]])

profit_loss = revenue - expensenses

print(profit_loss)

[[100 190 212]
 [150 344 390]
 [120 380 190]]
