<a href="https://colab.research.google.com/github/mngugi/Code_3_Camp/blob/main/Recap_Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

list1 = [1,2,3,4,5]
list2 = [11,12,13,14,15]

# convert the list into an array
j = np.array(list1)
i = np.array(list2)
# add
kadd = j+i
print(kadd)

#subtract

ksubtract = j - i
print(ksubtract)

#multiplication
kmultiple = j * i
print(kmultiple)

#dotproduct - scalar value
kdot = j @ i
print(kdot)

l = [23,36,96]
m = [85,95,65]

# cross function
ncross = np.cross(l,m)
print(ncross)

n = [9,8,5,6,7]
p = np. array(n)
x = 2

multi = p *x
print(multi)

[12 14 16 18 20]
[-10 -10 -10 -10 -10]
[11 24 39 56 75]
205
[-6780  6665  -875]
[18 16 10 12 14]


In [6]:

# distributive law under dot product
u = np.array([1,2,3])
v = np.array([4,5,6])
w = np.array([7,8,9])

d1 = u.dot(v+w)
d2 = u.dot(v) + u.dot(w)
print(d1 == d2)

True
